### ISSUE TITLE
Server Crash while exploring (fabric)

### ISSUE THREAD

**Issue by NolanHewitt** [YUNG-GANG/YUNGs-Better-Ocean-Monuments#13]
[crash-2023-10-06_04.53.22-server.txt](https://github.com/YUNG-GANG/YUNGs-Better-Ocean-Monuments/files/12829580/crash-2023-10-06_04.53.22-server.txt)

**Comment by Hunter-495** [comment]
Yeah, I ended up getting a crash as well, looking at logs in the modrinth launcher showed an error about "betteroceanmonuments:start", another error immediately afterward lists: 
"No starting jigsaw with Name betteroceanmonuments:anchor found in start pool betteroceanmonuments:starts"
I think something was messed up in the structure generation in 1.20.1.

**Comment by Hunter-495** [comment]
Here's the full error I got (It's short don't worry):
[Worker-Main-9/ERROR]:
 Couldn't load structure betteroceanmonuments:start
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3481) ~[?:?]
	at java.util.ArrayList.grow(ArrayList.java:237) ~[?:?]
	at java.util.ArrayList.addAll(ArrayList.java:678) ~[?:?]
	at net.minecraft.class_3499.method_28055(class_3499.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_3499.method_15177(class_3499.java:715) ~[client-intermediary.jar:?]
	at net.minecraft.class_3499.method_15183(class_3499.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485.method_21891(class_3485.java:235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485.method_15090(class_3485.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485.method_44231(class_3485.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485.method_15088(class_3485.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485$$Lambda$17531/0x0000000802eb8d00.apply(Unknown Source) ~[?:?]
	at net.minecraft.class_3485.method_44245(class_3485.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485$$Lambda$17834/0x0000000802f50708.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
	at net.minecraft.class_3485.method_15094(class_3485.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_3485.method_15091(class_3485.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_3781$$Lambda$17833/0x0000000802f504c8.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3781.method_27233(class_3781.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_3781.method_16627(class_3781.java:107) ~[client-intermediary.jar:?]
	at com.yungnickyoung.minecraft.yungsapi.world.structure.jigsaw.JigsawManager.getPosOfJigsawBlockWithName(JigsawManager.java:252) ~[YungsApi-1.20-Fabric-4.0.2.jar:?]
	at com.yungnickyoung.minecraft.yungsapi.world.structure.jigsaw.JigsawManager.getStartPiece(JigsawManager.java:187) ~[YungsApi-1.20-Fabric-4.0.2.jar:?]
	at com.yungnickyoung.minecraft.yungsapi.world.structure.jigsaw.JigsawManager.assembleJigsawStructure(JigsawManager.java:61) ~[YungsApi-1.20-Fabric-4.0.2.jar:?]
	at com.yungnickyoung.minecraft.yungsapi.api.YungJigsawManager.assembleJigsawStructure(YungJigsawManager.java:70) ~[YungsApi-1.20-Fabric-4.0.2.jar:?]
	at com.yungnickyoung.minecraft.yungsapi.world.structure.YungJigsawStructure.method_38676(YungJigsawStructure.java:197) ~[YungsApi-1.20-Fabric-4.0.2.jar:?]
	at net.minecraft.class_3195.method_47932(class_3195.java:199) ~[client-intermediary.jar:?]
	at net.minecraft.class_3195.method_41614(class_3195.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_41044(class_2794.java:513) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_41041(class_2794.java:466) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794$$Lambda$19620/0x0000000803202e40.accept(Unknown Source) ~[?:?]
[Worker-Main-9/ERROR]:
 No starting jigsaw with Name betteroceanmonuments:anchor found in start pool betteroceanmonuments:starts
